### ISSUE TITLE
Sensors are defined as text sensors rather than numeric sensors

### ISSUE THREAD

**Issue by FillR2** [tcarwash/home-assistant_noaa-space-weather#29]
Hi,

Thank you for this integration.

I'm using NOAA Space Weather version 1.1.0 on HA :
Home Assistant 2023.6.1
Operating System 10.2

The problem is that sensors, even if they have numeric values, are displayed as text sensors (see image below) rather than numeric sensors, thus no graphic charts (lines or bars) can be displayed.

Is it possible to change the sensor types to numeric ?

Thanks for your feedback.

![image](https://github.com/tcarwash/home-assistant_noaa-space-weather/assets/86425615/1d0b8c76-da9c-45fd-a49b-10147d569bed)

**Comment by mdisabato** [comment]
I am also having this issue. 

Thank you.

**Comment by tcarwash** [comment]
Hi all, thank you for your interest, it's been a while since I took a look at this code but since there's interest I'll pick it back up. I'll take a look at what @mdisabato posted, feel free to send a PR if you beat me to it

**Comment by tcarwash** [comment]
@mdisabato I took a look at your file. I'll do some testing, I can't remember if I converted the output to a string for any good reason. Maybe I just wanted that % sign on there, hard to tell what I was thinking.

**Comment by tcarwash** [comment]
This should be fixed by #31 

join me in the https://github.com/tcarwash/home-assistant_noaa-space-weather/discussions/31 to let me know if this is working how you expect it to.
