### ISSUE TITLE
A index does not match NOAA Space Weather value

### ISSUE THREAD

**Issue by StreamingMeeMee** [tcarwash/home-assistant_noaa-space-weather#33]
The A index sensor value does not match the value on the NOAA Space Weather website.  For example, the current value reported by NOAA is 36 but the value I see in HA is 9.

I have restarted HA with debug and will post updates if any relevant info is noted.

Thanks for this integration, BTW.  I was starting to gather sources to build something on my own and then stumbled across this - WIN!

73,  Tim
```

**Comment by StreamingMeeMee** [comment]
Also, it seems the Planetary K index is off as well.  I am seeing 0 while the NOAA site reports it as 1.  Solar flux is close; NOAA: 176, HA: 167.  What is the timing of the updates?

**Comment by wheirman** [comment]
`swpc.get_standard()` by default seems to return the first item from a list (for K, there is one measurement per minute over a period of 4 hours). So you get the value from 4 hours ago, not the current one.

I created a couple of PRs that update this:

https://github.com/tcarwash/swpclib/pull/8
https://github.com/tcarwash/home-assistant_noaa-space-weather/pull/34

**Comment by tcarwash** [comment]
Awesome, I'll take a look when I get a chance

**Comment by tcarwash** [comment]
In looking at this more closely it looks like maybe only K-index was backward (the NOAA APIs aren't standardized for 0th entry = newest data and I missed K-index)

I fixed K-index in swpclib v4.2.0 so it should return the newest data now. Fixing it at the library level will let us continue to take the first data point in swpc.get_standard() as normal. I'll just need to make a new version of this component that points at that version of v4.2.0 and we'll be getting the most recent data for all endpoints

Let me know if I'm missing something!

**Comment by tcarwash** [comment]
I think any outstanding incorrectly indexed endpoints are corrected in v2.0.1

Going to close this issue, let me know if I've got something wrong. 

Thank you very much for your input!
