### ISSUE TITLE
Deprecated async_add_job

### ISSUE THREAD

**Issue by Failure404** [tcarwash/home-assistant_noaa-space-weather#37]
Detected that custom integration 'noaa_space_weather' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/noaa_space_weather/__init__.py, line 54: hass.async_add_job(, please create a bug report at https://github.com/tcarwash/home-assistant_noaa-space-weather/issues

**Comment by tcarwash** [comment]
Should be resolved by #[da9e841](https://github.com/tcarwash/home-assistant_noaa-space-weather/commit/da9e841e211c5d3a04d12362cf391a5d79a197f4)
