### ISSUE TITLE
Installation link invalid

### ISSUE THREAD

**Issue by HypeLaser** [tcarwash/home-assistant_noaa-space-weather#49]
Hey. After rebooting and adding the Integration, the pop-up has a clickable link for information which is for:

https://github.com/tcarwash/noaa_space_weather

However, this link is invalid as the integration has been renamed. The correct URL should be:

https://github.com/tcarwash/home-assistant_noaa-space-weather

Thanks!

**Comment by tcarwash** [comment]
I'll get this fixed ASAP

**Comment by tcarwash** [comment]
I changed all mentions of this URL in the code, I think it was coming from the translations files. Which makes me think I probably need to have those regenerated somehow. Anyway, this fix will be in the next release. 

Thanks again! 

English commit is [here](https://github.com/tcarwash/home-assistant_noaa-space-weather/commit/b1f93cafa5cdd898961063e5087b35d566567d02
)

updated in other languages and comments of __init__.py as well.
