### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Womble-1** [tcarwash/home-assistant_noaa-space-weather#52]
Does the integration use the location of the HASS instance? 
Please can you add a bit more information on how to read the provided data, it doesn't (seem to) match the terminology on the NOAA. site. 

(i am trying to write an automation to trigger when there are good Aurora conditions at my location)

**Comment by tcarwash** [comment]
There's actually another custom integration by someone else that uses your location specifically for Aurora visibility probability triggers. 

This integration doesn't have any location specific (or any) settings. The data it brings into homeassistant is all global in scope and would be relevant anywhere.

If you are looking to trigger for when Aurora might be visible you'd probably want to set some threshold for planetary k index.

**Comment by tcarwash** [comment]
https://www.home-assistant.io/integrations/aurora/

**Comment by Womble-1** [comment]
That integration looks like just what i am after.  Thank you for taking the time to point me in the right direction.
