### ISSUE TITLE
No statistics found.

### ISSUE THREAD

**Issue by Cyberes** [tcarwash/home-assistant_noaa-space-weather#54]
## Version of the custom_component

2.0.1

## Describe the bug

When an entity from this component is added to a statistic graph, all stat types are grayed out and the graph displays `No statistics found.`

![image](https://github.com/user-attachments/assets/3590e13b-0844-4118-bd65-1b4896668b3b)

![image](https://github.com/user-attachments/assets/3e46aa2c-0768-4ea1-81e6-ecad12c10800)

Adding this to `extra_state_attributes` seems to fix the issue:

```
'state_class': 'measurement'
```

**Comment by tcarwash** [comment]
Thanks for this, I'll take a look when I get some time
